name: CI build
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: DerYeger/pnpm-setup-action@master
        with:
          node-version: latest
      - name: Build
        run: pnpm build
      - name: Compress action step
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          cwd: ./
          files: |
            ./build
          outPath: build.tar.gz
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            build.tar.gz
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build.tar.gz
